name: Manual - LibreTranslate (with models)

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: Version tag to build.
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  LOWER_REPO: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: Clone upstream
        uses: actions/checkout@v3
        with:
          repository: LibreTranslate/LibreTranslate
          ref: ${{ inputs.version_tag }}

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Convert repository name to lowercase
        id: lowercase-repo
        run: |
          echo "::set-output name=lowercase_repo::$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')"

      - name: Set lowercase repository name
        run: |
          echo "LOWER_REPO=${{ steps.lowercase-repo.outputs.lowercase_repo }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          build-args: with_models=true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.LOWER_REPO }}:${{ inputs.version_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
